config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # This could have been a solution but I would like to use it as a reference
  # namespace :api do
  #   namespace :v1 do
  #     resources :stores, only: [:index, :show] do
  #       resources :shoes, only: [:index, :show]
  #     end
  #   end
  # end

  root "stores#index"
  resources :stores, only: [:index] do
    get 'counter', to: 'stores#counter'
    get 'realtime'
    resources :shoes, only: [:index]
  end
  resources :stats, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  has_many :store_shoes
  has_many :stores, through: :store_shoes

  def inventory_by_store(store)
    store_shoes.find_by!(store: store).quantity
  end

  def is_below_threshold?(store)
    inventory_by_store(store) < InventoryManager.threshold
  end

  def is_below_restock_threshold?(store)
    inventory_by_store(store) < InventoryManager.restock_threshold
  end
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :store_shoe, optional: true
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_shoes
  has_many :shoes, through: :store_shoes

  def inventory
    store_shoes.sum(:quantity)
  end
end

app/models/store_shoe.rb
class StoreShoe < ApplicationRecord
  belongs_to :store
  belongs_to :shoe
  after_update :notify_inventory_manager, if: :quantity_below_threshold?
  # after_update :automatic_restock, if: :quantity_below_restock_threshold?
  after_update :create_stat

  private

  def quantity_below_threshold?
    quantity < InventoryManager.threshold && !quantity_below_restock_threshold?
  end

  def quantity_below_restock_threshold?
    quantity < InventoryManager.restock_threshold
  end

  def create_stat
    Stat.create(store_shoe: self, quantity: quantity)
  end

  # def automatic_restock
  #   puts "Automatic restock triggered for #{shoe.name} in #{store.name}"
  #   quantity_to_restock = InventoryManager.threshold - quantity
  #   StoreShoe.where(shoe:).order("quantity DESC").each do |store_restock|
  #     if store_restock.quantity - quantity_to_restock > InventoryManager.threshold
  #       transfer = store_restock.quantity - quantity_to_restock
  #       store_restock.update(quantity: store_restock.quantity - transfer)
  #       update(quantity: quantity + transfer)
  #     end
  #   end
  # end
  # def automatic_restock
  #   puts "Automatic restock triggered for #{shoe.name} in #{store.name}"
  #   quantity_to_restock = InventoryManager.threshold - quantity
  #   StoreShoe.where(shoe:).order("quantity DESC").each do |store_restock|
  #     stock_after_transfer = store_restock.quantity - quantity_to_restock

  #     if stock_after_transfer >= InventoryManager.threshold
  #       store_restock.update(quantity: stock_after_transfer)
  #       update(quantity: quantity + quantity_to_restock)
  #       break
  #     else
  #       adjusted_transfer = InventoryManager.threshold - store_restock.quantity
  #       store_restock.update(quantity: InventoryManager.threshold)
  #       update(quantity: quantity + adjusted_transfer)
  #     end
  #   end
  # end

  # While this is not ideal to trigger the email from the model,
  # We keep it here for the sake of the exercise
  # Also it is easy to test the email using the console
  def notify_inventory_manager
    InventoryManager.handle_notification(store, shoe, quantity)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_store
  def index
    @shoes = @store.shoes
    respond_to do |format|
      format.json { render 'index', status: :ok }
      format.html
    end
  end

  private

  def set_store
    begin
      @store = Store.find_by!(id: params[:store_id])
    rescue ActiveRecord::RecordNotFound
      head :not_found
    end
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def show
    @stats = Stat.where(store_shoe_id: params[:id]).pluck(:created_at, :quantity).to_h
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
    render do |format|
      format.json { render json: @stores }
      format.html { }
    end
  end

  def realtime
    @store = Store.find_by!(id: params[:store_id])
    @shoes = @store.shoes
    respond_to do |format|
      format.html
    end
  end

  def counter
    @store = Store.find(params[:store_id])
    render partial: "stores/counter", locals: { store: @store }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body class="bg-gray-100">
  <div class="min-h-screen flex items-center justify-center">
    <div class="w-full max-w-4xl px-6">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/shoes/index.html.erb
<div class="hero bg-gray-200 p-8 flex justify-between items-center">
  <h1 class="text-3xl font-bold text-gray-700">
    <%= @store.name %> - Shoes Management
  </h1>
  <a href="/" class="text-gray-400 hover:text-gray-600 transition duration-150 ease-in-out">Home</a>
</div>
<div data-controller="shoe" data-id="<%= @store.id %>" data-stores-shoe-url="<%= store_shoes_path(@store) %>"
  class="max-w-4xl mx-auto my-8 p-4 bg-gray-100 shadow-lg rounded-lg">
  <ul class="list-none space-y-2">
    <% @shoes.each do |shoe| %>
      <li class="flex justify-between items-center p-4 border-b border-gray-200 hover:bg-blue-200 hover:border-blue-400">
        <div>
          <span class="text-gray-500 text-xl">
            <%= link_to shoe.name,
                stat_path(shoe.id),
                class: "text-blue-600 hover:text-blue-800 font-semibold" %>
          </span>
          <div class="py-4 whitespace-nowrap text-sm text-gray-500">
            <div class="inline-flex items-center px-3 py-1 rounded-full text-lg font-semibold bg-blue-100 text-blue-800">
              Shoes count:
              <%= turbo_frame_tag "shoe_#{shoe.id}" do %>
                <%= shoe.inventory_by_store(@store) %>
              <% end %>
            </div>
          </div>
        </div>
        <%= turbo_frame_tag "shoe_#{shoe.id}_threshold", class: "#{shoe.is_below_threshold?(@store) && !shoe.is_below_restock_threshold?(@store) ? 'block' : 'hidden'}" do %>
          <div class="animate-pulse">
            <?xml version="1.0" encoding="utf-8"?>
            <svg width="40px" height="40px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 6C12.5523 6 13 6.44772 13 7V13C13 13.5523 12.5523 14 12 14C11.4477 14 11 13.5523 11 13V7C11 6.44772 11.4477 6 12 6Z" fill="#ffae00"/>
            <path d="M12 16C11.4477 16 11 16.4477 11 17C11 17.5523 11.4477 18 12 18C12.5523 18 13 17.5523 13 17C13 16.4477 12.5523 16 12 16Z" fill="#ffae00"/>
            <path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2ZM4 12C4 16.4183 7.58172 20 12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4C7.58172 4 4 7.58172 4 12Z" fill="#ffae00"/>
            </svg>
          </div>
        <% end %>
        <%= turbo_frame_tag "shoe_#{shoe.id}_restock_threshold", class: "#{shoe.is_below_restock_threshold?(@store) ? 'block' : 'hidden'}" do %>
          <div>
            <?xml version="1.0" encoding="utf-8"?>
            <svg width="40px" height="40px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 6C12.5523 6 13 6.44772 13 7V13C13 13.5523 12.5523 14 12 14C11.4477 14 11 13.5523 11 13V7C11 6.44772 11.4477 6 12 6Z" fill="#fe0000"/>
            <path d="M12 16C11.4477 16 11 16.4477 11 17C11 17.5523 11.4477 18 12 18C12.5523 18 13 17.5523 13 17C13 16.4477 12.5523 16 12 16Z" fill="#fe0000"/>
            <path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2ZM4 12C4 16.4183 7.58172 20 12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4C7.58172 4 4 7.58172 4 12Z" fill="#fe0000"/>
            </svg>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/stats/show.html.erb
<%= line_chart @stats %>

app/views/stores/_counter.html.erb
<%= store.inventory %>

app/views/stores/index.html.erb
<div class="hero bg-gray-200 p-8">
  <h1 class="text-center text-3xl font-bold text-gray-700">Stores Management</h1>
</div>
<div data-controller="store" class="max-w-4xl mx-auto my-8 p-4 bg-gray-100 shadow-lg rounded-lg">
  <ul class="list-none space-y-2">
    <% @stores.each do |store| %>
      <li class="flex justify-between items-center p-4 border-b border-gray-200 hover:bg-blue-200 hover:border-blue-400">
        <div>
          <span class="text-gray-500 text-xl">
            <%= link_to store.name, store_shoes_path(store.id), class: "text-blue-600 hover:text-blue-800 font-semibold" %>
          </span>
          <div class="py-4 whitespace-nowrap text-sm text-gray-500">
            <div class="inline-flex items-center px-3 py-1 rounded-full text-lg font-semibold bg-blue-100 text-blue-800">
              Shoes count:
              <%= turbo_frame_tag "store_#{store.id}_count", data: {
                store_counter_url: store_counter_path(store)
              } do %>
                <%= render partial: "stores/counter", locals: { store: store } %>
              <% end %>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/stores/realtime.html.erb
<div class="hero bg-gray-200 p-8 flex justify-between items-center">
  <h1 class="text-3xl font-bold text-gray-700">
    <%= @store.name %> - Shoes Management
  </h1>
  <a href="/" class="text-gray-400 hover:text-gray-600 transition duration-150 ease-in-out">Home</a>
</div>
<div data-controller="realtime" data-id="<%= @store.id %>" data-store="<%= @store.name %>" data-stores-shoe-url="<%= store_shoes_path(@store) %>"
  class="max-w-4xl mx-auto my-8 p-4 bg-gray-100 shadow-lg rounded-lg">
  <ul class="list-none space-y-2">
    <% @shoes.each do |shoe| %>
      <li class="flex justify-between items-center p-4 border-b border-gray-200 hover:bg-blue-200 hover:border-blue-400">
        <div>
          <span class="text-gray-500 text-xl">
            <%= link_to shoe.name,
                stat_path(shoe.id),
                class: "text-blue-600 hover:text-blue-800 font-semibold" %>
          </span>
          <div class="py-4 whitespace-nowrap text-sm text-gray-500">
            <div class="inline-flex items-center px-3 py-1 rounded-full text-lg font-semibold bg-blue-100 text-blue-800">
              Shoes count:
              <%= turbo_frame_tag "shoe_#{shoe.name.downcase}" do %>
                <%= shoe.inventory_by_store(@store) %>
              <% end %>
            </div>
          </div>
        </div>
        <%= turbo_frame_tag "shoe_#{shoe.name.downcase}_threshold", class: "#{shoe.is_below_threshold?(@store) && !shoe.is_below_restock_threshold?(@store) ? 'block' : 'hidden'}" do %>
          <div class="animate-pulse">
            <?xml version="1.0" encoding="utf-8"?>
            <svg width="40px" height="40px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 6C12.5523 6 13 6.44772 13 7V13C13 13.5523 12.5523 14 12 14C11.4477 14 11 13.5523 11 13V7C11 6.44772 11.4477 6 12 6Z" fill="#ffae00"/>
            <path d="M12 16C11.4477 16 11 16.4477 11 17C11 17.5523 11.4477 18 12 18C12.5523 18 13 17.5523 13 17C13 16.4477 12.5523 16 12 16Z" fill="#ffae00"/>
            <path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2ZM4 12C4 16.4183 7.58172 20 12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4C7.58172 4 4 7.58172 4 12Z" fill="#ffae00"/>
            </svg>
          </div>
        <% end %>
        <%= turbo_frame_tag "shoe_#{shoe.name.downcase}_restock_threshold", class: "#{shoe.is_below_restock_threshold?(@store) ? 'block' : 'hidden'}" do %>
          <div>
            <?xml version="1.0" encoding="utf-8"?>
            <svg width="40px" height="40px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 6C12.5523 6 13 6.44772 13 7V13C13 13.5523 12.5523 14 12 14C11.4477 14 11 13.5523 11 13V7C11 6.44772 11.4477 6 12 6Z" fill="#fe0000"/>
            <path d="M12 16C11.4477 16 11 16.4477 11 17C11 17.5523 11.4477 18 12 18C12.5523 18 13 17.5523 13 17C13 16.4477 12.5523 16 12 16Z" fill="#fe0000"/>
            <path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2ZM4 12C4 16.4183 7.58172 20 12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4C7.58172 4 4 7.58172 4 12Z" fill="#fe0000"/>
            </svg>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>